In [1]:
import numpy as np
import cv2
import math
image=cv2.imread('Lenna.png')

In [2]:
kernel_type = ["1. Box filter", "2. First Order Derivative Filter-xy", "3. Prewitt-xy", "4. Sobel-xy", "5. Roberts-xy","6. Prewitt-x", "7. Prewitt-y", "8. Sobel-x","9. Sobel-y", "10. Roberts-x", "11. Roberts-y"]
print("Different Kernel Types: " ,*kernel_type, sep=" \n")
select_kernel = int(input("Enter the type of kernel: "))

Different Kernel Types:  
1. Box filter 
2. First Order Derivative Filter-xy 
3. Prewitt-xy 
4. Sobel-xy 
5. Roberts-xy 
6. Prewitt-x 
7. Prewitt-y 
8. Sobel-x 
9. Sobel-y 
10. Roberts-x 
11. Roberts-y
Enter the type of kernel: 10


In [3]:
derivative_x = np.array([[-1, 1]])
derivative_y = np.array([[-1],[ 1]])
prewitt_x = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])
prewitt_y = np.array([[1, 1, 1], [0, 0, 0], [-1, -1, -1]])
sobel_x = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
sobel_y = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])
roberts_x = np.array([[0, 1], [-1, 0]])
roberts_y = np.array([[1, 0], [0, -1]])
box_filter = 1/9*(np.ones([3,3]))

In [4]:
pad_type = ["1. Zero", "2. Wrap Around", "3. Copy Edge", "4. Reflect Across Edge"]
print("Types of padding available: " ,*pad_type, sep=" \n")
select_padding = int(input("Enter the type of padding: "))

Types of padding available:  
1. Zero 
2. Wrap Around 
3. Copy Edge 
4. Reflect Across Edge
Enter the type of padding: 3


In [5]:
def conv2(f, w, pad):
    if(w==1):
        kernel1 = box_filter
        kernel2 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    if(w==2):
        kernel1= derivative_x
        kernel2 = derivative_y
    elif(w==3):
        kernel1 = prewitt_x
        kernel2 = prewitt_y
    elif(w==4):
        kernel1 = sobel_x
        kernel2 = sobel_y
    elif(w==5):
        kernel1 = roberts_x
        kernel2 = roberts_y
    elif(w==6):
        kernel1 = prewitt_x
        kernel2 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    elif(w==7):
        kernel1 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
        kernel2 = prewitt_y
    elif(w==8):
        kernel1 = sobel_x
        kernel2 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    elif(w==9):
        kernel1 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
        kernel2 = sobel_y
    elif(w==10):
        kernel1 = roberts_x
        kernel2 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    elif(w==11):
        kernel1 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
        kernel2 = roberts_y
    kernel1 = np.fliplr(np.flipud(kernel1))
    kernel2 = np.fliplr(np.flipud(kernel2))
    #x is the padding width which varies based on kernel size
    x=int((max(kernel1.shape[0],kernel1.shape[1],kernel2.shape[1],kernel2.shape[0]))/2)
    #padded image is created based on kernel size
    if(len(f.shape) == 3):
    	image_padded =np.zeros((f.shape[0]+(x*2),f.shape[1]+(x*2),f.shape[2]),dtype=np.uint8)
    else:
    	image_padded=np.zeros([f.shape[0]+(x*2),f.shape[1]+(x*2)])
    m = image_padded.shape[0]
    n = image_padded.shape[1]
    #Zero Padding
    image_padded[x: m-x, x: n-x] = f
    #Wrap Around Padding
    if(pad==2):
        for i in range(1,x+1):
            image_padded[m-i, x: n-x] = image_padded[x-1+i, x: n-x]
            image_padded[i-1, x: n-x] = image_padded[m-x-i, x: n-x]
            image_padded[x: m-x, i-1] = image_padded[x: m-x, n-x-i]
            image_padded[x: m-x, n-i] = image_padded[x: m-x, x-1+i]
            image_padded[0:x, 0:x] = image_padded[m-x-x: m-x, n-x-x: n-x]
            image_padded[m-x:m, n-x:n] = image_padded[x: 2*x, x: 2*x]
            image_padded[0:x, n-x:n] = image_padded[m-x-x: m-x, x: 2*x]
            image_padded[m-x:m, 0:x] = image_padded[x: 2*x, n-x-x: n-x]
    #Copy Edge Padding
    elif(pad==3):
        for i in range(1,x+1):
            image_padded[m-x:m, x: n-x] = image_padded[m-x-1, x: n-x]
            image_padded[0:x, x: n-x] = image_padded[x+1, x: n-x]
            image_padded[x: m-x, i-1] = image_padded[x: m-x, x+1]
            image_padded[x: m-x, n-i] = image_padded[x: m-x, n-x-1]
            image_padded[0:x, 0:x] = image_padded[x,x]
            image_padded[m-x:m, n-x:n] = image_padded[m-x-1,n-x-1]
            image_padded[0:x, n-x:n] = image_padded[x,n-x]
            image_padded[m-x:m, 0:x] = image_padded[m-x,x]
    #Reflect Across Edge
    elif(pad==4):
        for i in range(1,x+1):
            image_padded[m-i, 0: n] = image_padded[(m-1)-(2*x)+i, 0: n]
            image_padded[0: m, n-i] = image_padded[0: m, (n-1)-(2*x)+i]
            image_padded[i-1, 0: n] = image_padded[(2*x)-i, 0: n]
            image_padded[0: m, i-1] = image_padded[0: m, (2*x)-i]

    #output image is initiated with zeros with the same dimensions and type as input image
    output_image = np.zeros_like(f)
    
    #convolution function is performed here based on the selected color and gray images:
    for x in range(f.shape[0]):
            for y in range(f.shape[1]):
                #For color image
                if(len(f.shape)==3):
                    output_image[x,y,2]=math.sqrt(((kernel1*image_padded[x:x + kernel1.shape[0], y:y + kernel1.shape[1], 2]).sum())**2 + ((kernel2*image_padded[x:x + kernel2.shape[0], y:y + kernel2.shape[1], 2]).sum())**2)
                    output_image[x,y,1]=math.sqrt(((kernel1*image_padded[x:x + kernel1.shape[0], y:y + kernel1.shape[1], 1]).sum())**2 + ((kernel2*image_padded[x:x + kernel2.shape[0], y:y + kernel2.shape[1], 1]).sum())**2)
                    output_image[x,y,0]=math.sqrt(((kernel1*image_padded[x:x + kernel1.shape[0], y:y + kernel1.shape[1], 0]).sum())**2 + ((kernel2*image_padded[x:x + kernel2.shape[0], y:y + kernel2.shape[1], 0]).sum())**2)
                #For gray scale image
                else:  
                    output_image[x,y]=math.sqrt(((kernel1*image_padded[x:x + kernel1.shape[0], y:y + kernel1.shape[1]]).sum())**2 + ((kernel2*image_padded[x:x + kernel2.shape[0], y:y + kernel2.shape[1]]).sum())**2)
    return output_image
    
    

In [6]:
output_parta = conv2(image, select_kernel, select_padding)

In [7]:
kernel_type = ["1. Box filter", "2. First Order Derivative Filter-xy", "3. Prewitt-xy", "4. Sobel-xy", "5. Roberts-xy","6. Prewitt-x", "7. Prewitt-y", "8. Sobel-x","9. Sobel-y", "10. Roberts-x", "11. Roberts-y"]
print("Different Kernel Types: " ,*kernel_type, sep=" \n")
select_kernel = int(input("Enter the type of kernel: "))
pad_type = ["1. Zero", "2. Wrap Around", "3. Copy Edge", "4. Reflect Across Edge"]
print("Types of padding available: " ,*pad_type, sep=" \n")
select_padding = int(input("Enter the type of padding: "))
#unit impulse image
unit_impulse = np.zeros([1024,1024])
unit_impulse[512,512] = 255
#convolution function on the unit impulse image
unit_impulse_output = conv2(unit_impulse, select_kernel, select_padding)
#Displaying the center pixels of the impulse output to see the effect of convolution
print("Impulse_output", unit_impulse_output[510:515,510:515], sep=" \n")

Different Kernel Types:  
1. Box filter 
2. First Order Derivative Filter-xy 
3. Prewitt-xy 
4. Sobel-xy 
5. Roberts-xy 
6. Prewitt-x 
7. Prewitt-y 
8. Sobel-x 
9. Sobel-y 
10. Roberts-x 
11. Roberts-y
Enter the type of kernel: 10
Types of padding available:  
1. Zero 
2. Wrap Around 
3. Copy Edge 
4. Reflect Across Edge
Enter the type of padding: 3
Impulse_output 
[[  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0. 255.   0.]
 [  0.   0. 255.   0.   0.]
 [  0.   0.   0.   0.   0.]]


In [8]:
cv2.imshow("Input Image(a)", image)
cv2.imshow("Result Image(a)", output_parta)
cv2.imshow("Input Image(b)", unit_impulse)
cv2.imshow("Result Image(b)", unit_impulse_output)
cv2.waitKey(0)
cv2.destroyAllWindows()